# Generated by Django 3.1.5 on 2021-01-04 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='어드민유저', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(4, '네글자 이상 입력해주세요.')], verbose_name='닉네임'),
            preserve_default=False,
        ),
    ]
