# Generated by Django 3.1.5 on 2021-01-04 15:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, validators=[django.core.validators.MinLengthValidator(10, '열 글자 이상 입력해주세요.')], verbose_name='타이틀')),
                ('sub_title', models.CharField(blank=True, max_length=255, verbose_name='부제')),
                ('thumbnail', models.ImageField(upload_to='worldcup_thumbnail/%Y/%m/%d', verbose_name='썸네일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, verbose_name='이미지 제목')),
                ('player', models.ImageField(upload_to='worldcup/%Y/%m/%d/%h', verbose_name='이미지')),
                ('world_cup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldcupapp.worldcup', verbose_name='월드컵')),
            ],
        ),
    ]
